[versions]
lombok-mapstruct-binding = "0.2.0"
mapstruct = "1.6.3"
spring-boot = "4.0.2"
spring-dependency-management = "1.1.7"
spring-dotenv = "5.1.0"
telegram = "9.3.0"
testcontainers = "2.0.3"

[libraries]
# BOMs / Platforms
spring-dotenv-bom = { module = "me.paulschwarz:spring-dotenv-bom", version.ref = "spring-dotenv" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }

# Spring Boot (Versions managed by spring-boot plugin)
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }

# Database & Utilities (Versions managed by Spring Boot dependency management)
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
lombok = { module = "org.projectlombok:lombok" }
postgresql = { module = "org.postgresql:postgresql" }
springboot4-dotenv = { module = "me.paulschwarz:springboot4-dotenv", version.ref = "spring-dotenv" }

# Telegram
telegram-client = { module = "org.telegram:telegrambots-client", version.ref = "telegram" }
telegram-starter = { module = "org.telegram:telegrambots-springboot-longpolling-starter", version.ref = "telegram" }

# MapStruct & Lombok Additions
lombok-mapstruct-binding = { module = "org.projectlombok:lombok-mapstruct-binding", version.ref = "lombok-mapstruct-binding" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

# Testcontainers
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }